mqtt: 
  server: 192.168.8.2

serialport:
  device: "/dev/tty.usbmodem411"
  baudrate: "9600"

googlecalendar:
  calendarID: "alr.st_t4do0ippogfurs00brmpgfhre0%40group.calendar.google.com"
  apiKey: "127336077993-68nj95v0g50cmp51ijcto80o3pfvmnfh.apps.googleusercontent.com"
  apiSecret: "d5zzAvXajo4f3Z8evyC_2K0R"
  refreshToken: "1/AzO8EynE7Re9vDhp5CJyKwsRW_SDWsUn7UIWOgz--UU"

webinterface:
  host: "192.168.8.2"
  port: "8080"